Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace stockproject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using stockproject.Enititys;
using stockproject.Models;

namespace stockproject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly StockprojectContext db = new StockprojectContext();
        public void OnGet()
        {

        }
        public ActionResult OnPostLogInUser()
        {
             
            Enititys.User user = new Enititys.User();
            user = (from t1 in db.User
                    where t1.Username == username && t1.Password == password
                    select t1).SingleOrDefault();

            if (user != null)
            {

                var claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.Name, user.Username));

                var claimIdenties = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var claimPrincipal = new ClaimsPrincipal(claimIdenties);
                var authenticationManager = Request.HttpContext;

                authenticationManager.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrincipal, new AuthenticationProperties() { IsPersistent = false });

                //return RedirectToPage("/Stock/Admin/Admin");

                return RedirectToPage("/Stock/Product");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Invalid username or password.");
                return Page();
            }

        }
        //public List<User> MyProperty = new List<User>();
        [BindProperty]
        public string username { get; set; }
        [BindProperty]
        public string password { get; set; }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace stockproject.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
    Layout = "~/Pages/Shared/_LayoutEmpty.cshtml";
}
<form method="post" style="padding-top:5px">
    <div class="form-group">
        <div class="input-group shadow-sm">
            <div class="input-group-prepend">
                <span class="input-group-text"></span>
            </div>
            @Html.TextBoxFor(m => m.username, new { @class = "form-control", @placeholder = "Your Username*" })
        </div>
    </div>
    <div class="form-group">
        <div class="input-group shadow-sm">
            <div class="input-group-prepend">
                <span class="input-group-text"></span>
            </div>
            @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Your Password *" })
        </div>
    </div>
    <div class="form-group">
        <button asp-page-handler="LogInUser" class="btn btn-success"> Login</button>
    </div>
    @Html.ValidationSummary(true, "", new { @style = "color:rgb(255, 255, 255)" })
</form>