Pages/Stock/Admin/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using stockproject.Enititys;
using stockproject.Models;

namespace stockproject.Pages.Admin
{
    public class AdminModel : PageModel
    {
        private  readonly StockprojectContext db = new StockprojectContext();

        
        public void OnGet()
        {
            //var q2 = from a in db.User
            //         join e in db.FormIn on a.Userid equals e.Userid

            //         select new { a.Userid,a.Username,e.Createdate, e.Status };
            var q2 = (from t1 in db.FormIn
                      orderby t1.Status ascending
                      select new { t1.FormInid , t1.Status, t1.Createdate});
                      
                     
            foreach (var item in q2)
            {
                var status = "";
                if (item.Status ==true)
                {
                    status = "True";
                }else
                {
                    status = "False";
                }

                list.Add(new QueryAdmin
                {

                    id = item.FormInid,
                   Subject = "FormIn",
                    Createdate = item.Createdate,
                    Status = status

                });
            }
            var q3= (from t1 in db.FormOut
                      orderby t1.Status ascending
                      select new { t1.FormOutid, t1.Status, t1.Createdate });


            foreach (var item in q3)
            {
                var status = "";
                if (item.Status == true)
                {
                    status = "True";
                }
                else
                {
                    status = "False";
                }

                list.Add(new QueryAdmin
                {

                    id = item.FormOutid,
                    Subject = "FormOut",
                    Createdate = item.Createdate,
                    Status = status

                });
            }

        }
        
        public ActionResult OnPostAAA()
        {
            //var a = MyProperty1;
            return Page();
        }
        //public IActionResult OnPost()
        //{
        //    return Content("");
        //}
        public PartialViewResult OnGetContactModalPartial()
        {
            // this handler returns _ContactModalPartial
            return new PartialViewResult
            {
                //ViewName = "_ContactModalPartial",
                //ViewData = new ViewDataDictionary<Contact>(ViewData, new Contact { })
            };
        }
        public ActionResult OnPostVALUE(int id,string type)
        {
         
            return RedirectToPage("./confirmstatus", "OnGet", new { formid = id ,formtype=type });

        }
    
        [BindProperty]
        public List<QueryAdmin> list { get; set; } = new List<QueryAdmin>();
        public List<string> id { get; set; }

    }
}

Pages/Stock/Admin/confirmstatus.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.Models;

namespace stockproject
{
    public class confirmstatusModel : PageModel
    {
 

        private StockprojectContext db = new StockprojectContext();
        public List<AdminConfirm> list { get; set; } = new List<AdminConfirm>();
        public void OnGet(int formid , string formtype)
        {
            if (formtype == "FormIn")
            {
           
                ViewData["id"] = formid;
                ViewData["type"] = "Form IN";
                var q2 = from a in db.ProductFormIn
                         join b in db.FormIn on a.FormInid equals b.FormInid
                         join c in db.User on b.Userid equals c.Userid
                         join d in db.Product on a.ProductId equals d.Productid
                         where (b.FormInid == formid)
                         select new { c.Username, b.Createdate, d.Productname, a.Qty, a.Price };
                foreach (var item in q2)
                {

                    ViewData["date"] = item.Createdate;
                    ViewData["name"] = item.Username;
                    list.Add(new AdminConfirm
                    {
                        product = item.Productname,
                        qty = item.Qty,
                       // Createdate = item.Createdate,
                        price = item.Price
                        //name= item.Username
                    });
                }
            }
            else
            {
                ViewData["id"] = formid;
                ViewData["type"] = "Form OUT";
                var q2 = from a in db.ProductFormOut
                     join b in db.FormOut on a.FormOutid equals b.FormOutid
                     join c in db.User on b.Userid equals c.Userid
                     join d in db.Product on a.ProductId equals d.Productid
                         where (b.FormOutid == formid)
                         select new { c.Username, b.Createdate ,d.Productname,a.Qty, a.Price };

                foreach (var item in q2)
                {

                    ViewData["date"] = item.Createdate;
                    ViewData["name"] = item.Username;
                    list.Add(new AdminConfirm
                    {
                        product = item.Productname,
                        qty = item.Qty,
                        // Createdate = item.Createdate,
                        price = item.Price
                        //name= item.Username
                    });
                }

            }
        }

        public ActionResult OnPostCONFIRM(string id,string type)
        {
            if (type == "Form IN")
            {
               
                var q = from c in db.FormIn
                         where c.FormInid == Int32.Parse(id)
                         select c;
                foreach (FormIn c in q)
                {
                    c.Status = true;
                }
                db.SaveChanges();

            }
            else if(type == "Form OUT")
            {
                var q = from d in db.FormOut
                        where d.FormOutid == Int32.Parse(id)
                        select d;
                foreach (FormOut d in q)
                {
                    d.Status = true;
                }
                db.SaveChanges();
            }
            return RedirectToPage("./Admin", "OnGet");

        }
        public ActionResult OnPostREJECT(string id, string type)
        {

            if (type == "Form IN")
            {

            }
            else if (type == "Form OUT")
            {

            }
            return RedirectToPage("./Admin", "OnGet");

        }
    }
}

Pages/Stock/CreateForm.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace stockproject.Pages.Stock
{
    public class CreateFormModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Stock/CreateProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;

namespace stockproject
{
    public class CreateProductModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();
        public void OnGet()
        {
        }
        public ActionResult OnPostToCreate()
        {
            var a = name;
            var a1 = price;
            Product table = new Product();
            table.Productname = name;
            table.Qty = 1;
            table.Price = Int32.Parse(price);
            table.Userid = 1;
            table.Modifydate = DateTime.Now;

            db.Product.Add(table);
            db.SaveChanges();
            return RedirectToPage("./Product", "OnGet");
        }
        [BindProperty]
        public string name { get; set; }
        [BindProperty]
        public string price { get; set; }
    }
}

Pages/Stock/Product.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.Models;

namespace stockproject.Pages.Stock
{
    public class ProductModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();
        public List<Product> list { get; set; } = new List<Product>();
        public void OnGet()
        {
            var q = (from t1 in db.Product
                      orderby t1.Productname ascending
                      select new { t1.Productname, t1.Qty, t1.Price});


            foreach (var item in q)
            {

                list.Add(new Product
                {

                    Productname = item.Productname,
                    Qty = item.Qty,
                    Price = item.Price,

                });
            }
        }
    }
}

Pages/Stock/User/User.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using stockproject.Models;

namespace stockproject.Pages.User
{
    public class UsersModel : PageModel
    {
        public ActionResult OnGet(string A1)
        {
            MyProperty = new List<Class> {
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"} 
            };

            return Page();
        }
        public ActionResult OnPostAAA()
        {
            var a = MyProperty1;
           return Page();
        }
        [BindProperty]
        public int MyProperty1 { get; set; }

        [BindProperty]
        public List<Class> MyProperty { get; set; } = new List<Class>();

    }
}

Pages/Stock/CreateForm.cshtml
@page
@model stockproject.Pages.Stock.CreateFormModel
@{
    ViewData["Title"] = "CreateForm";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>CreateForm</h1>

Pages/Stock/CreateProduct.cshtml
@page
@model stockproject.CreateProductModel
@{
    ViewData["Title"] = "CreateProduct";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

    <form method="post">

        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                                <h5 class="card-title">Create Product </h5>
                            </div>
                            <br>



                            <div class="row">
                                <div class="col-md-12">
                                
                                        <div class="form-group">
                                            <label for="formGroupExampleInput">Product Name</label>
                                            <input type="text" class="form-control" name ="name"  placeholder="Test5">
                                        </div>
                                        <div class="form-group">
                                            <label for="formGroupExampleInput2">Price</label>
                                      

                                            <input type="number" class="form-control" name="price" placeholder="100">
                                        </div>
                                 
                                </div>
                            </div>

                            <div class="row justify-content-end">
                                <div class="row">

                                    <div class="col-5">
                                       
                                            <button class="btn btn-success" asp-page-handler="ToCreate">Confirm</button>
                                            @*<button class="btn btn-success">Confirm </button>
                                            <input type="hidden" name="id" value="@ViewData["id"]" />
                                            <input type="hidden" name="type" value="@ViewData["type"]" />*@
                                       
                                    </div>

                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
        </form>

Pages/Stock/Product.cshtml
@page
@model stockproject.Pages.Stock.ProductModel
@{
    ViewData["Title"] = "Product";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

    <div class="container">
        <div class="row justify-content-md-center">
         
            <div class="col-md-auto">
                <h3> Product</h3>
            </div>

        </div>
    </div>
        <br />
    <div class="container">
  
        <div class="row">

            <div class="col-md-8 offset-md-2">
                <div class="card">
                    <div class="card-header">
                        <div class="row justify-content-end">

                            <form asp-page-handler="/Stock/CreateProduct" method="get">
                                <button type="submit" class="btn btn-danger" asp-area="" asp-page="/Stock/CreateProduct">ADD </button>
                            </form>
                   
                        </div>
                        </div>
                    <div class="card-body">



                        <div class="row">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th style='text-align:center;'>No.</th>
                                        <th style='text-align:center;'>Product Name</th>
                                        <th style='text-align:center;'>QTY</th>
                                        <th style='text-align:center;'>Price</th>

                                    </tr>
                                </thead>

                                <tbody style="height: 250px; overflow-y: auto; overflow-x: hidden;">


                                    @for (int i = 0; i < Model.list.Count; i++)
                                    {

                                        <tr>
                                            <td style='text-align:center;'>@(i + 1)</td>
                                            <td style='text-align:center;'>@Model.list[i].Productname</td>
                                            <td style='text-align:center;'>@Model.list[i].Qty</td>

                                            <td style='text-align:center;'>@Model.list[i].Price</td>

                                        </tr>
                                    }

                                </tbody>
                            </table>


                        </div>
                            @*<div class="row justify-content-end">
                <div class="row">

                    <div class="col-5">
                        <form asp-page-handler="CONFIRM" method="post">
                            <button class="btn btn-success">Confirm </button>
                            <input type="hidden" name="id" value="@ViewData["id"]" />
                            <input type="hidden" name="type" value="@ViewData["type"]" />
                        </form>
                    </div>
                    <div class="col-5">
                        <form asp-page-handler="REJECT" method="post">
                            <button class="btn btn-danger">Reject </button>
                            <input type="hidden" name="id" value="@ViewData["id"]" />
                            <input type="hidden" name="type" value="@ViewData["type"]" />
                        </form>
                    </div>
                </div>

            </div>*@
                        </div>
                    </div>
            </div>

        </div>

    </div>