Pages/Stock/Admin/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using stockproject.Enititys;
using stockproject.Models;

namespace stockproject.Pages.Admin
{
    public class AdminModel : PageModel
    {
        private  readonly StockprojectContext db = new StockprojectContext();

        
        public void OnGet()
        {
            //var q2 = from a in db.User
            //         join e in db.FormIn on a.Userid equals e.Userid

            //         select new { a.Userid,a.Username,e.Createdate, e.Status };
            var q2 = (from t1 in db.FormIn
                      orderby t1.Status ascending
                      select new { t1.FormInid , t1.Status, t1.Createdate});
                      
                     
            foreach (var item in q2)
            {
                var status = "";
                if (item.Status ==true)
                {
                    status = "True";
                }else
                {
                    status = "False";
                }

                list.Add(new QueryAdmin
                {

                    id = item.FormInid,
                   Subject = "FormIn",
                    Createdate = item.Createdate,
                    Status = status

                });
            }
            var q3= (from t1 in db.FormOut
                      orderby t1.Status ascending
                      select new { t1.FormOutid, t1.Status, t1.Createdate });


            foreach (var item in q3)
            {
                var status = "";
                if (item.Status == true)
                {
                    status = "True";
                }
                else
                {
                    status = "False";
                }

                list.Add(new QueryAdmin
                {

                    id = item.FormOutid,
                    Subject = "FormOut",
                    Createdate = item.Createdate,
                    Status = status

                });
            }

        }
        
        public ActionResult OnPostAAA()
        {
            //var a = MyProperty1;
            return Page();
        }
        //public IActionResult OnPost()
        //{
        //    return Content("");
        //}
        public PartialViewResult OnGetContactModalPartial()
        {
            // this handler returns _ContactModalPartial
            return new PartialViewResult
            {
                //ViewName = "_ContactModalPartial",
                //ViewData = new ViewDataDictionary<Contact>(ViewData, new Contact { })
            };
        }
        public ActionResult OnPostVALUE(int id,string type)
        {
         
            return RedirectToPage("./confirmstatus", "OnGet", new { formid = id ,formtype=type });

        }
    
        [BindProperty]
        public List<QueryAdmin> list { get; set; } = new List<QueryAdmin>();
        public List<string> id { get; set; }

    }
}

Pages/Stock/Admin/confirmstatus.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.Models;

namespace stockproject
{
    public class confirmstatusModel : PageModel
    {
 

        private StockprojectContext db = new StockprojectContext();
        public List<AdminConfirm> list { get; set; } = new List<AdminConfirm>();
        public void OnGet(int formid , string formtype)
        {
            if (formtype == "FormIn")
            {
           
                ViewData["id"] = formid;
                ViewData["type"] = "Form IN";
                var q2 = from a in db.ProductFormIn
                         join b in db.FormIn on a.FormInid equals b.FormInid
                         join c in db.User on b.Userid equals c.Userid
                         join d in db.Product on a.ProductId equals d.Productid
                         where (b.FormInid == formid)
                         select new { c.Username, b.Createdate, d.Productname, a.Qty, a.Price };
                foreach (var item in q2)
                {

                    ViewData["date"] = item.Createdate;
                    ViewData["name"] = item.Username;
                    list.Add(new AdminConfirm
                    {
                        product = item.Productname,
                        qty = item.Qty,
                       // Createdate = item.Createdate,
                        price = item.Price
                        //name= item.Username
                    });
                }
            }
            else
            {
                ViewData["id"] = formid;
                ViewData["type"] = "Form OUT";
                var q2 = from a in db.ProductFormOut
                     join b in db.FormOut on a.FormOutid equals b.FormOutid
                     join c in db.User on b.Userid equals c.Userid
                     join d in db.Product on a.ProductId equals d.Productid
                         where (b.FormOutid == formid)
                         select new { c.Username, b.Createdate ,d.Productname,a.Qty, a.Price };

                foreach (var item in q2)
                {

                    ViewData["date"] = item.Createdate;
                    ViewData["name"] = item.Username;
                    list.Add(new AdminConfirm
                    {
                        product = item.Productname,
                        qty = item.Qty,
                        // Createdate = item.Createdate,
                        price = item.Price
                        //name= item.Username
                    });
                }

            }
        }

        public ActionResult OnPostCONFIRM(string id,string type)
        {
            if (type == "Form IN")
            {
               
                var q = from c in db.FormIn
                         where c.FormInid == Int32.Parse(id)
                         select c;
                foreach (FormIn c in q)
                {
                    c.Status = true;
                }
                db.SaveChanges();

            }
            else if(type == "Form OUT")
            {
                var q = from d in db.FormOut
                        where d.FormOutid == Int32.Parse(id)
                        select d;
                foreach (FormOut d in q)
                {
                    d.Status = true;
                }
                db.SaveChanges();
            }
            return RedirectToPage("./Admin", "OnGet");

        }
        public ActionResult OnPostREJECT(string id, string type)
        {

            if (type == "Form IN")
            {

            }
            else if (type == "Form OUT")
            {

            }
            return RedirectToPage("./Admin", "OnGet");

        }
    }
}

Pages/Stock/CreateForm.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace stockproject.Pages.Stock
{
    public class CreateFormModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Stock/CreateProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;

namespace stockproject
{
    public class CreateProductModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();
        public void OnGet()
        {
        }
        public ActionResult OnPostToCreate()
        {
            var a = name;
            var a1 = price;
            Product table = new Product();
            table.Productname = name;
            table.Qty = 1;
            table.Price = Int32.Parse(price);
            table.Userid = 1;
            table.Modifydate = DateTime.Now;

            db.Product.Add(table);
            db.SaveChanges();
            return RedirectToPage("./Product", "OnGet");
        }
        [BindProperty]
        public string name { get; set; }
        [BindProperty]
        public string price { get; set; }
    }
}

Pages/Stock/Product.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using stockproject.Enititys;
using stockproject.Models;

namespace stockproject.Pages.Stock
{
    public class ProductModel : PageModel
    {
        private StockprojectContext db = new StockprojectContext();
        public List<Product> list { get; set; } = new List<Product>();
        public void OnGet()
        {
            var q = (from t1 in db.Product
                      orderby t1.Productname ascending
                      select new { t1.Productname, t1.Qty, t1.Price});


            foreach (var item in q)
            {

                list.Add(new Product
                {

                    Productname = item.Productname,
                    Qty = item.Qty,
                    Price = item.Price,

                });
            }
        }
    }
}

Pages/Stock/User/User.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using stockproject.Models;

namespace stockproject.Pages.User
{
    public class UsersModel : PageModel
    {
        public ActionResult OnGet(string A1)
        {
            MyProperty = new List<Class> {
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"},
            new Class { A1 = "2" , A2 = "1"} 
            };

            return Page();
        }
        public ActionResult OnPostAAA()
        {
            var a = MyProperty1;
           return Page();
        }
        [BindProperty]
        public int MyProperty1 { get; set; }

        [BindProperty]
        public List<Class> MyProperty { get; set; } = new List<Class>();

    }
}

Pages/Stock/Admin/Admin.cshtml
@page
@model stockproject.Pages.Admin.AdminModel
@*@model IEnumerable<stockproject.Models.QueryAdmin>*@

@{
    ViewData["Title"] = "Admin";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@*<h1 id ="sho" >Admin</h1>

    <a href="" data-ajax="true" data-ajax-url="?handler=partial" data-ajax-update="#panel">Click here</a>
    <div id="panel">
        <p>@ViewData["Message"] from the Hello World partial at @DateTime.Now</p>
    </div>
    <button  class="btn btn-primary"  data-url="@Url.Page("Admin", "ContactModalPartial")">
        Add contact
    </button>
    <button type="button"data-ajax-method="post" class="btn btn-primary" data-ajax="true" data-toggle="ajax-modal" data-url="@Url.Page("Admin", "VALUE")">
        Add contact2
    </button>*@




@*<div class="container">
    <div class="row">

        <div class="col-md-3 ml-auto">
            <form asp-page-handler="CONFIRM" method="post">
                <button class="btn btn-success">Create Confirm</button>
            </form>
        </div>
    </div>
</div>*@

<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Subject</th>
                <th>Createdate</th>
                <th>Status</th>

            </tr>
        </thead>

        <tbody style="height: 250px; overflow-y: auto; overflow-x: hidden;">

            @*@foreach (var item in Model.list)
                {
                <tr>
                    <td>
                        <button asp-page-handler="VALUE" name="id" value="@item.Userid.ToString()">
                            @item.Userid.ToString()
                        </button>
                    </td>
                    @Html.HiddenFor(value => item.Userid)
                    <td>
                        @Html.DisplayFor(model => item.Username)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Createdate)

                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Status)

                    </td>

                </tr>

                }*@
            @for (int i = 0; i < Model.list.Count; i++)
            {

                @*<form asp-page-handler="VALUE" method="post">
                        <button class="btn btn-default">View</button>
                        <input type="hidden" name="id" value="@Model.list[i].id" />
                    </form>*@
                <tr>
                    <td>
                        @if (Model.list[i].Subject == "FormIn")
                        {
                            <form asp-page-handler="VALUE" method="post">
                                <button asp-page-handler="VALUE" class="btn btn-success">@(i + 1)</button>
                                <input type="hidden" name="id" value="@Model.list[i].id" />
                                <input type="hidden" name="type" value="@Model.list[i].Subject" />
                            </form>

                        }
                        else
                        {

                            <form asp-page-handler="VALUE" method="post">
                                <button asp-page-handler="VALUE" class="btn btn-danger">@(i + 1)</button>
                                <input type="hidden" name="id" value="@Model.list[i].id" />
                                <input type="hidden" name="type" value="@Model.list[i].Subject" />
                            </form>

                        }

                    </td>
                    <td>@Model.list[i].Subject</td>
                    @*@Html.HiddenFor(value => value.list[i].Subject)*@
                    <td>@Model.list[i].Createdate</td>
                    <td>@Model.list[i].Status</td>

                </tr>
            }

        </tbody>
    </table>

</div>
@*</form>*@
<div id="divloading" style="margin: 0px; padding: 0px; position: fixed; right: 0px;
        top: 0px; width: 100%; height: 100%; background-color:#ffffff; z-index: 300001;
        opacity: .8; filter: alpha(opacity=80);display:none">
    <div style="position: absolute; top: 40%; left: 40%; color: black;">

    </div>
</div>
@*<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>*@

<div id="myModal2" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                @*@using (Html.BeginForm("Register", "Home"))
                    {
                        <div class="row">
                            id : @Html.TextBoxFor(x => x.Id)
                        </div>
                        <div class="row">
                            Name : @Html.TextBoxFor(x => x.Name)
                        </div>

                        <div class="row">
                            <input type="submit" value="send data" />
                        </div>

                    }*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

@*<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel">Title</h4>
                </div>
                <div class="modal-body">
                    @TempData["WarningMessage"]
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Confirm</button>
                </div>
            </div>
        </div>
    </div>*@


@*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Launch demo modal
    </button>*@

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
@*<script>
        function Success() {

            alert("For111111");

        }
        function Failure() {

            alert("Form Failed");
        }


    </script>*@

Pages/Stock/Admin/confirmstatus.cshtml
@page
@model stockproject.confirmstatusModel
@{
    ViewData["Title"] = "confirmstatus";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
    @*<div class="container">
        <div class="row">
        
            <div class="col-md-3 ml-auto">
                <form asp-page-handler="CONFIRM" method="post">
                    <button class="btn btn-success">Create Confirm</button>
                </form>
            </div>
            </div>
        </div>*@
      
        <div class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                                <h5 class="card-title">@ViewData["type"] </h5>
                            </div>
                            <br><br>

                            <div class="row justify-content-between">
                                <div class="col-4">
                                    <p>Create By : @ViewData["name"]</p>
                                </div>
                                <div class="col-5">
                                    <p>CreateDate : @ViewData["date"]</p>
                                </div>
                            </div>

                            <div class="row">
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>No.</th>
                                            <th>Product Name</th>
                                            <th>QTY</th>
                                            <th>Price</th>

                                        </tr>
                                    </thead>

                                    <tbody style="height: 250px; overflow-y: auto; overflow-x: hidden;">


                                        @for (int i = 0; i < Model.list.Count; i++)
                                        {

                                            <tr>
                                                <td>@(i + 1)</td>
                                                <td>@Model.list[i].product</td>
                                                <td>@Model.list[i].qty</td>

                                                <td>@Model.list[i].price</td>

                                            </tr>
                                        }

                                    </tbody>
                                </table>

                            </div>

                            <div class="row justify-content-end">
                                <div class="row">

                                    <div class="col-5">
                                        <form asp-page-handler="CONFIRM" method="post">
                                            <button class="btn btn-success">Confirm </button>
                                            <input type="hidden" name="id" value="@ViewData["id"]" />
                                            <input type="hidden" name="type" value="@ViewData["type"]" />
                                        </form>
                                    </div>
                                    <div class="col-5">
                                        <form asp-page-handler="REJECT" method="post">
                                            <button class="btn btn-danger">Reject </button>
                                            <input type="hidden" name="id" value="@ViewData["id"]" />
                                            <input type="hidden" name="type" value="@ViewData["type"]" />
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>